// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRIL-uIzeB24qv7PhN0OFTx0-j78ntHqM',
    appId: '1:400047673953:web:0337e5bfd0295adadf9020',
    messagingSenderId: '400047673953',
    projectId: 'inspection-app-flutter',
    authDomain: 'inspection-app-flutter.firebaseapp.com',
    storageBucket: 'inspection-app-flutter.appspot.com',
    measurementId: 'G-SZLB4JLZ11',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkm2RKaCgrV3BHTChtfHVXcAevCpTncjo',
    appId: '1:400047673953:android:1b9a2aa443790315df9020',
    messagingSenderId: '400047673953',
    projectId: 'inspection-app-flutter',
    storageBucket: 'inspection-app-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDZTfa8JYUnW2VKQY9sytXJUIRigp0q9Y',
    appId: '1:400047673953:ios:79040c9f3894719fdf9020',
    messagingSenderId: '400047673953',
    projectId: 'inspection-app-flutter',
    storageBucket: 'inspection-app-flutter.appspot.com',
    iosBundleId: 'com.example.inspectionAppFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDZTfa8JYUnW2VKQY9sytXJUIRigp0q9Y',
    appId: '1:400047673953:ios:eeec587444683d2ddf9020',
    messagingSenderId: '400047673953',
    projectId: 'inspection-app-flutter',
    storageBucket: 'inspection-app-flutter.appspot.com',
    iosBundleId: 'com.example.inspectionAppFlutter.RunnerTests',
  );
}
